/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.addsubtractmultiply;
import java.util.Random;
/**
 *
 * @author kevmm
 */
public class MainWindow extends javax.swing.JFrame {
    int score = 0;
    int count = 0;
    

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_num1 = new javax.swing.JTextField();
        tf_num2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_num3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lb_result = new javax.swing.JLabel();
        buttonCheck = new javax.swing.JButton();
        lb_score = new javax.swing.JLabel();
        lb_realscore = new javax.swing.JLabel();
        lb_totalcount = new javax.swing.JLabel();
        jl_numbers = new javax.swing.JLabel();
        jl_subtract1 = new javax.swing.JLabel();
        jl_subtract2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_sub1 = new javax.swing.JTextField();
        buttonCheck2 = new javax.swing.JButton();
        buttonsubtract = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jl_multi1 = new javax.swing.JLabel();
        jl_multi2 = new javax.swing.JLabel();
        buttonmultiply = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_multi1 = new javax.swing.JTextField();
        buttonmulti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Number 1");

        jLabel2.setText("Number 2");

        jLabel3.setText("Input Answer");

        jButton1.setText("Add It!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Add");

        buttonCheck.setText("Check");
        buttonCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCheckMouseClicked(evt);
            }
        });

        lb_score.setText("Total Score:");

        lb_realscore.setText("0");

        lb_totalcount.setText("Total Count");

        jl_numbers.setText("#");

        jl_subtract1.setText("0");

        jl_subtract2.setText("0");

        jLabel7.setText("Subtract");

        jLabel8.setText("Input Answer");

        tf_sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sub1ActionPerformed(evt);
            }
        });

        buttonCheck2.setText("Check ");
        buttonCheck2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCheck2MouseClicked(evt);
            }
        });

        buttonsubtract.setText("Subtract");
        buttonsubtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsubtractMouseClicked(evt);
            }
        });

        jLabel13.setText("Multiply");

        jl_multi1.setText("0");

        jl_multi2.setText("0");

        buttonmultiply.setText("Multiply");
        buttonmultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonmultiplyMouseClicked(evt);
            }
        });

        jLabel5.setText("Input Answer");

        buttonmulti.setText("Check");
        buttonmulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonmultiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl_multi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(jl_multi2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_subtract1)
                                    .addComponent(jLabel7)
                                    .addComponent(jl_subtract2))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addComponent(buttonmultiply))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_num3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_multi1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_score)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_realscore, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lb_totalcount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_result, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(buttonCheck)
                        .addGap(57, 57, 57)
                        .addComponent(buttonCheck2)
                        .addGap(43, 43, 43)
                        .addComponent(buttonmulti)))
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jl_subtract1)
                            .addComponent(jl_multi1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_subtract2)
                            .addComponent(jl_multi2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(buttonsubtract)
                            .addComponent(buttonmultiply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(tf_sub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tf_multi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCheck)
                            .addComponent(buttonCheck2)
                            .addComponent(buttonmulti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_score)
                            .addComponent(lb_realscore)
                            .addComponent(lb_totalcount)
                            .addComponent(jl_numbers)))
                    .addComponent(lb_result, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Generate random numbers ~
        int num1, num2;
        Random r = new Random();
        num1 = r.nextInt(10) + 1;
        num2 = r.nextInt(10) + 1;
        tf_num1.setText(String.valueOf(num1));
        tf_num2.setText(String.valueOf(num2));
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void buttonCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCheckMouseClicked
        // TODO add your handling code here:
       int userInput, answer, num1, num2;
       
       
       userInput = Integer.parseInt(tf_num3.getText());
       num1 = Integer.parseInt(tf_num1.getText());
       num2 = Integer.parseInt(tf_num2.getText());
       answer = num1 + num2;
       count = count +1;
       if (userInput == answer)
       {
           lb_result.setText("Correct");
           score = score +1;
       }
       else
       {
        lb_result.setText("Incorrect");
               
       }
        lb_realscore.setText(String.valueOf(score));
        jl_numbers.setText(String.valueOf(count));
        
    }//GEN-LAST:event_buttonCheckMouseClicked

    private void tf_sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sub1ActionPerformed
        // TODO add your handling code here:
        
       
       
      
        
                                          
    }//GEN-LAST:event_tf_sub1ActionPerformed

    private void buttonCheck2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCheck2MouseClicked
        // check subtraction
         int userInput, answer2, num4, num5;
       
       
       userInput = Integer.parseInt(tf_sub1.getText());
       num4 = Integer.parseInt(jl_subtract1.getText());
       num5 = Integer.parseInt(jl_subtract2.getText());
       answer2 = num4 - num5;
       count = count + 1;
       if (userInput == answer2)
       {
           lb_result.setText("Correct!!!");
           score = score +1;
       }
       else
       {
        lb_result.setText("Incorrect!!!");
               
       }
        lb_realscore.setText(String.valueOf(score));
        jl_numbers.setText(String.valueOf(count));
    }//GEN-LAST:event_buttonCheck2MouseClicked

    private void buttonmultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonmultiMouseClicked
        // Multiply CHECK!!
        int userInput, answer3, num6, num7;
       
       
       userInput = Integer.parseInt(tf_multi1.getText());
       num6 = Integer.parseInt(jl_multi1.getText());
       num7 = Integer.parseInt(jl_multi2.getText());
       answer3 = num6 * num7;
       count = count +1;
       if (userInput == answer3)
       {
           lb_result.setText("Correct");
           score = score +1;
       }
       else
       {
        lb_result.setText("Incorrect");
               
       }
        lb_realscore.setText(String.valueOf(score));
        jl_numbers.setText(String.valueOf(count));
    }//GEN-LAST:event_buttonmultiMouseClicked

    private void buttonsubtractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsubtractMouseClicked
        // real subtraction
      int num4, num5;
        Random r = new Random();
        num4 = r.nextInt(10) - 1;
        num5 = r.nextInt(10) - 1;
        jl_subtract1.setText(String.valueOf(num4));
        jl_subtract2.setText(String.valueOf(num5));
    }//GEN-LAST:event_buttonsubtractMouseClicked

    private void buttonmultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonmultiplyMouseClicked
        // real multiplication:
        int num6, num7;
        Random r = new Random();
        num6 = r.nextInt(10) * 1;
        num7 = r.nextInt(10) * 1;
        jl_multi1.setText(String.valueOf(num6));
        jl_multi2.setText(String.valueOf(num7));
    }//GEN-LAST:event_buttonmultiplyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheck;
    private javax.swing.JButton buttonCheck2;
    private javax.swing.JButton buttonmulti;
    private javax.swing.JButton buttonmultiply;
    private javax.swing.JButton buttonsubtract;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jl_multi1;
    private javax.swing.JLabel jl_multi2;
    private javax.swing.JLabel jl_numbers;
    private javax.swing.JLabel jl_subtract1;
    private javax.swing.JLabel jl_subtract2;
    private javax.swing.JLabel lb_realscore;
    private javax.swing.JLabel lb_result;
    private javax.swing.JLabel lb_score;
    private javax.swing.JLabel lb_totalcount;
    private javax.swing.JTextField tf_multi1;
    private javax.swing.JTextField tf_num1;
    private javax.swing.JTextField tf_num2;
    private javax.swing.JTextField tf_num3;
    private javax.swing.JTextField tf_sub1;
    // End of variables declaration//GEN-END:variables
}
